### PR TITLE
Cleans up the code by fixing indentation and closing some unclosed tags

### PR DESCRIPTION
**Pull request by HaleAT**

### CODE REVIEW

**Comment by fossildog117** [comment]
Having authentication problems with the GitHub app.

can someone upload this GIF to Site/images

[cid:08BBECBB-AE47-46E6-A454-F30E0BCD9C0C@studentcom.co.uk]
On 14 Feb 2016, at 23:13, Alex Hale <notifications@github.com<mailto:notifications@github.com>> wrote:

Merged #17https://github.com/fossildog117/Coding_Curriculum/pull/17.

**Comment by HaleAT** [comment]
What gif?

**Comment by fossildog117** [comment]
see attachment
[cid:85A403C9-9AAC-4D3C-A1FE-D6EFD7B17C02@studentcom.co.uk]
On 15 Feb 2016, at 10:03, Alex Hale <notifications@github.com<mailto:notifications@github.com>> wrote:

What gif?

**Comment by HaleAT** [comment]
Yep I cannot see that, I will leave it for someone else

**Comment by fossildog117** [comment]
try this, I made another gif for binary searches

**Pull request merged**
