### PR TITLE
Avoid use of pre in code boxes

### PR DESCRIPTION
**Pull request by HaleAT**

### CODE REVIEW

**Comment by fossildog117** [comment]
Alex the eduroam in Oxford has slowed down massively for some reason. Can you download the submission I made on moodle then edit it with the current Site file on the GitHub then upload the new submission onto moodle

Sent from my iPhone

On 12 Feb 2016, at 19:39, Alex Hale <notifications@github.com<mailto:notifications@github.com>> wrote:

Merged #10https://github.com/fossildog117/Coding_Curriculem/pull/10.

##

**Comment by fossildog117** [comment]
If not possible let me know and I will run home to finish it.

Cheers

Nathan

Sent from my iPhone

On 12 Feb 2016, at 19:39, Alex Hale <notifications@github.com<mailto:notifications@github.com>> wrote:

Merged #10https://github.com/fossildog117/Coding_Curriculem/pull/10.

##

**Comment by HaleAT** [comment]
I can do, just to clarify, you want me to download the existing submission and replace the entire Site directory with the current one in master?

**Comment by fossildog117** [comment]
My files are in the current submission but not on the Site directory on GitHub. So we need to merge them together

Sent from my iPhone

On 12 Feb 2016, at 19:58, Alex Hale <notifications@github.com<mailto:notifications@github.com>> wrote:

I can do, just to clarify, you want me to download the existing submission and replace the entire Site directory with the current one in master?

##

**Comment by HaleAT** [comment]
Are there any changes to the files we have been working on in the git repo or is it just new pages unlisted on the index?

**Comment by fossildog117** [comment]
I have added my pages into the index file. It's worth opening the index file I submitted this morning to see what's exactly on it

Sent from my iPhone

On 12 Feb 2016, at 20:05, Alex Hale <notifications@github.com<mailto:notifications@github.com>> wrote:

Are there any changes to the files we have been working on in the git repo or is it just new pages unlisted on the index?

##

**Comment by HaleAT** [comment]
You also have two files not linked to by the index, do you still want them included?

**Comment by fossildog117** [comment]
No those files don't have the CSS implemented yet so I left them out

Sent from my iPhone

On 12 Feb 2016, at 20:17, Alex Hale <notifications@github.com<mailto:notifications@github.com>> wrote:

You also have two files not linked to by the index, do you still want them included?

##

**Comment by HaleAT** [comment]
Right I have added your other files to the git now, I will upload the Site folder as it stands now from the git repo

**Comment by fossildog117** [comment]
Thanks Alex

Sent from my iPhone

On 12 Feb 2016, at 20:29, Alex Hale <notifications@github.com<mailto:notifications@github.com>> wrote:

Right I have added your other files to the git now, I will upload the Site folder as it stands now from the git repo

##

**Comment by HaleAT** [comment]
Submitted although the documentation is wrong as the compiling works fine... The issue is $stdout goes to the web console. It is a pdf so I can't change it easily...

**Comment by HaleAT** [comment]
Also I think I can adjust your lessons so the output works for them

**Comment by fossildog117** [comment]
Could you copy and paste documentation and then edit it on another document.

Sent from my iPhone

On 12 Feb 2016, at 20:38, Alex Hale <notifications@github.com<mailto:notifications@github.com>> wrote:

Also I think I can adjust your lessons so the output works for them

##

**Comment by HaleAT** [comment]
Why do you use functions in the first lesson without explaining them at all........

**Comment by HaleAT** [comment]
I think your variables lesson, 1) doesn't cover variables really, 2) explains none of what it uses.... The strings is fine, we might want to say the codeBox doesn't work on the page though

**Comment by fossildog117** [comment]
They're easy to infer

Sent from my iPhone

On 12 Feb 2016, at 20:45, Alex Hale <notifications@github.com<mailto:notifications@github.com>> wrote:

Why do you use functions in the first lesson without explaining them at all........

##

**Comment by fossildog117** [comment]
Oh it was meant to be a lesson on integers but i originally called it variables.html

Sent from my iPhone

On 12 Feb 2016, at 20:53, Alex Hale <notifications@github.com<mailto:notifications@github.com>> wrote:

I think your variables lesson, 1) doesn't cover variables really, 2) explains none of what it uses.... The strings is fine, we might want to say the codeBox doesn't work on the page though

##

**Comment by HaleAT** [comment]
why have functions, particularly with default values then...

**Comment by HaleAT** [comment]
Why not just get them to use it as a calculator or something...

**Comment by fossildog117** [comment]
Good idea, I didn't think of implementing that

Sent from my iPhone

On 12 Feb 2016, at 21:00, Alex Hale <notifications@github.com<mailto:notifications@github.com>> wrote:

Why not just get them to use it as a calculator or something...

##

**Comment by fossildog117** [comment]
You can take away the function of you want

Sent from my iPhone

On 12 Feb 2016, at 20:59, Alex Hale <notifications@github.com<mailto:notifications@github.com>> wrote:

why have functions, particularly with default values then...

##

**Comment by HaleAT** [comment]
I created a pull request that implements that change, if you like it then merge it and I will resubmit

**Comment by fossildog117** [comment]
I can't access the Internet with my laptop at the moment. Can't connect to eduroam merge the files and submit I guess

Sent from my iPhone

On 12 Feb 2016, at 21:23, Alex Hale <notifications@github.com<mailto:notifications@github.com>> wrote:

I created a pull request that implements that change, if you like it then merge it and I will resubmit

##

**Comment by HaleAT** [comment]
Submitted

**Pull request merged**
